### PR TITLE
Styling for desktop and mobile

### PR DESCRIPTION
**Pull request by Artini04**
I made a style/design for the whole site for desktop and mobile view. Didn't touch the JavaScript.

Here are all of the stuff I changed/added:

- Changed `button` to `input[type="button"]` to match buttons height to input.
- Added `:root` at the top of the css so that it's easier to edit the theme of the site.
- Placed most of the elements inside a `div` for better and easier styling.
- Placed the entirety of the codes in the body inside `main` 
- Removed `br` in the HTML document and some margins in the CSS.  Flexbox will take care of the spacing.

### CODE REVIEW

**Comment by Jokaes** [comment]
Looks nice imo. I think the shiny page is a bit broken in mobile tho.

Are you in the discord?

**Comment by Artini04** [comment]
@Jokaes Yep! artini04#3704

**Comment by Jokaes** [comment]
Oh no I meant in the Infinite Fusion server

**Comment by Artini04** [comment]
@Jokaes Ah, no.

**Comment by Artini04** [comment]
I joined the discord server. I'll be honest, it didn't cross my mind that this is managed by an organization/group. I'm like this is a neat site but the mobile view is kinda janky, so I clone the repo and did some styling.

**Comment by Aegide** [comment]
Can you please use "git rebase" so your work is compatible with the latest version of the calc ?

There are conflicts right now.

**Comment by Artini04** [comment]
@Aegide I'm still new with git. How can I "git rebase"?

**Comment by Artini04** [comment]
@Aegide ignore my latest commit, I messed up

**Comment by Artini04** [comment]
Everything's set!

**Comment by Artini04** [comment]
@Aegide hey, I'm closing this pull request. After thinking about it, the old style is actually better, simpler, and it doesn't complicate things.

I still wanted to fix the mobile view so I'll think of a simpler approach.

**Comment by Aegide** [comment]
Sure, no worries.

**Pull request closed without merging**
